//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRS.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;

    [MetadataType(typeof(Distress))]
    public partial class distress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public distress()
        {
            this.d_detail = new HashSet<d_detail>();
        }
    
        public int distress_id { get; set; }
        public string distress_name { get; set; }
        public string distress_description { get; set; }
        public System.DateTime distress_created_date { get; set; }
        public string distress_created_by { get; set; }
        public System.DateTime distress_last_modified_date { get; set; }
        public string distress_last_modified_by { get; set; }
        public int distress_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_detail> d_detail { get; set; }
    }
}
