//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRS.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DRSEntities : DbContext
    {
        public DRSEntities()
            : base("name=DRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<d_detail> d_detail { get; set; }
        public virtual DbSet<distress> distresses { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<licence> licences { get; set; }
        public virtual DbSet<owner> owners { get; set; }
        public virtual DbSet<radio_station> radio_station { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vessel_owner_ref> vessel_owner_ref { get; set; }
        public virtual DbSet<vessel> vessels { get; set; }
        public virtual DbSet<error_log> error_log { get; set; }
    }
}
