//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_log
    {
        public int error_no { get; set; }
        public string error_controller_name { get; set; }
        public string error_method_name { get; set; }
        public string error_exception { get; set; }
        public string error_remarks { get; set; }
    }
}
