//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRS.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;

    [MetadataType(typeof(Owner))]
    public partial class owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public owner()
        {
            this.vessel_owner_ref = new HashSet<vessel_owner_ref>();
        }
    
        public int owner_id { get; set; }
        public string owner_name { get; set; }
        public string owner_nic { get; set; }
        public string owner_address { get; set; }
        public string owner_tele { get; set; }
        public System.DateTime owner_created_date { get; set; }
        public string owner_created_by { get; set; }
        public System.DateTime owner_last_modified_date { get; set; }
        public string owner_last_modified_by { get; set; }
        public int owner_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vessel_owner_ref> vessel_owner_ref { get; set; }
    }
}
