//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRS.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;

    [MetadataType(typeof(Registration))]
    public partial class registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registration()
        {
            this.vessels = new HashSet<vessel>();
        }
    
        public int registration_id { get; set; }
        public string registration_code { get; set; }
        public string registration_description { get; set; }
        public System.DateTime registration_created_date { get; set; }
        public string registration_created_by { get; set; }
        public System.DateTime registration_last_modified_date { get; set; }
        public string registration_last_modified_by { get; set; }
        public int registration_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vessel> vessels { get; set; }
    }
}
