//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRS.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;

    [MetadataType(typeof(User))]
    public partial class user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_nic { get; set; }
        public string user_address { get; set; }
        public string user_tele { get; set; }
        public string user_username { get; set; }
        public int mcs_id { get; set; }
        public System.DateTime user_created_date { get; set; }
        public string user_created_by { get; set; }
        public System.DateTime user_last_modified_date { get; set; }
        public string user_last_modified_by { get; set; }
        public int user_status { get; set; }
    
        public virtual radio_station radio_station { get; set; }
    }
}
