//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRS.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;

    [MetadataType(typeof(Vessel))]
    public partial class vessel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vessel()
        {
            this.d_detail = new HashSet<d_detail>();
            this.licences = new HashSet<licence>();
            this.vessel_owner_ref = new HashSet<vessel_owner_ref>();
        }
    
        public int vessel_id { get; set; }
        public string vessel_no { get; set; }
        public int vessel_pending_approval { get; set; }
        public string vessel_name { get; set; }
        public string vessel_color { get; set; }
        public string vessel_loa { get; set; }
        public System.DateTime vessel_created_date { get; set; }
        public string vessel_created_by { get; set; }
        public System.DateTime vessel_last_modified_date { get; set; }
        public string vessel_last_modified_by { get; set; }
        public int vessel_status { get; set; }
        public int registration_id { get; set; }
        public int district_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_detail> d_detail { get; set; }
        public virtual district district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<licence> licences { get; set; }
        public virtual registration registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vessel_owner_ref> vessel_owner_ref { get; set; }
    }
}
